# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verify',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
