# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_account_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='verify',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
