# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20180923_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(upload_to='pictures')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Account')),
            ],
            options={
                'db_table': 'Picture',
            },
        ),
    ]
